var API_BASE_URL = window.location.port === "5000"
    ? ""
    : (window.location.protocol === "file:" || window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" ? "http://localhost:5000" : "");

// ==========================================
// Resume Editor Workspace Controller
// ==========================================

const resume_id = localStorage.getItem("resume_id");
const user_id = localStorage.getItem("user_id");

let previewData = null;
let activeTemplateId = null;
let templatesList = [];
let currentStep = "contacts";

const stepsOrder = ["contacts", "education", "experience", "skills", "projects", "certifications"];

// ==========================================
// Initialization
// ==========================================
window.addEventListener("DOMContentLoaded", async () => {
    // Session Check
    const userId = localStorage.getItem("user_id");
    if (!userId) {
        alert("Please login first.");
        window.location.href = "login.html";
        return;
    }

    await loadWorkspaceData();
    setupEventListeners();
    setupRealtimeBinding();
});

// ==========================================
// Load Initial Data
// ==========================================
let isDirty = false;
let isAutoSaveRunning = false;

function markDirty() {
    isDirty = true;
    const badge = document.getElementById("draftStatusBadge");
    if (badge) {
        if (!resume_id) {
            badge.innerHTML = `<i class="fa-solid fa-clock"></i> Unsaved Session Draft`;
            badge.style.color = "#f59e0b";
        } else {
            badge.innerHTML = `<i class="fa-solid fa-spinner fa-spin"></i> Saving draft...`;
            badge.style.color = "#f59e0b";
        }
    }
}

async function triggerAutoSave() {
    // Only auto-save to DB if a resume_id has been generated by explicit Save Resume
    if (!isDirty || isAutoSaveRunning || !resume_id) return;
    isAutoSaveRunning = true;
    try {
        const payload = {
            user_id: user_id || 1,
            resume_id: resume_id,
            resume_name: (previewData && previewData.resume_title) ? previewData.resume_title : "Untitled Resume",
            template_id: activeTemplateId || 1,
            is_draft: true,
            resume_json: previewData
        };
        await fetch(`${API_BASE_URL}/api/resume/save-json`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });
        isDirty = false;
        const badge = document.getElementById("draftStatusBadge");
        if (badge) {
            badge.innerHTML = `<i class="fa-solid fa-cloud-check"></i> ✓ Saved to Database`;
            badge.style.color = "#10b981";
        }
    } catch (err) {
        console.error("Auto-save error:", err);
    } finally {
        isAutoSaveRunning = false;
    }
}

setInterval(triggerAutoSave, 3000);

// Explicit Save Resume Handler (Creates resume_id & saves custom sections in PostgreSQL)
async function saveResumeToDatabase() {
    const saveBtn = document.getElementById("btnSaveResume");
    if (saveBtn) {
        saveBtn.classList.add("disabled");
        saveBtn.innerHTML = `<i class="fa-solid fa-spinner fa-spin"></i> Saving to Database...`;
    }

    try {
        const uploadPayload = {
            user_id: user_id || 1,
            resume_id: resume_id || null,
            resume_title: (previewData && previewData.resume_title) ? previewData.resume_title : "My Resume",
            template_id: activeTemplateId || 1,
            upload_confidence: (previewData && previewData.upload_confidence) ? previewData.upload_confidence : 100,
            is_draft: false,
            personal: (previewData && previewData.personal_details && previewData.personal_details[0]) ? previewData.personal_details[0] : {},
            education: (previewData && previewData.education) ? previewData.education : [],
            experience: (previewData && previewData.experience) ? previewData.experience : [],
            skills: (previewData && previewData.skills) ? previewData.skills : [],
            projects: (previewData && previewData.projects) ? previewData.projects : [],
            certifications: (previewData && previewData.certifications) ? previewData.certifications : [],
            languages: (previewData && previewData.languages) ? previewData.languages : [],
            custom_sections: (previewData && previewData.custom_sections) ? previewData.custom_sections : []
        };

        console.log("Saving full resume payload to PostgreSQL database...", uploadPayload);
        const res = await fetch(`${API_BASE_URL}/api/resume/save-full-upload`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(uploadPayload)
        });

        const saveResult = await res.json();
        if (saveResult.success && (saveResult.resume_id || saveResult.ref_id)) {
            const newResumeId = saveResult.resume_id || saveResult.ref_id;
            resume_id = newResumeId;

            localStorage.setItem("resume_id", newResumeId);
            localStorage.setItem(`resume_template_id_${newResumeId}`, activeTemplateId);
            sessionStorage.removeItem("temp_resume_parsed_data");

            // Update URL cleanly without reloading
            window.history.replaceState(null, "", `editor.html?resume_id=${newResumeId}`);

            const badge = document.getElementById("draftStatusBadge");
            if (badge) {
                badge.innerHTML = `<i class="fa-solid fa-cloud-check"></i> ✓ Saved to Database`;
                badge.style.color = "#10b981";
            }

            alert("Resume saved successfully to PostgreSQL database!");
        } else {
            alert(saveResult.message || "Failed to save resume. Please try again.");
        }
    } catch (err) {
        console.error("Save Resume Error:", err);
        alert("An error occurred while saving resume to database.");
    } finally {
        if (saveBtn) {
            saveBtn.classList.remove("disabled");
            saveBtn.innerHTML = `<i class="fa-solid fa-cloud-arrow-up"></i> Save Resume`;
        }
    }
}

// Bind Save Resume Button
document.addEventListener("DOMContentLoaded", () => {
    const saveBtn = document.getElementById("btnSaveResume");
    if (saveBtn) {
        saveBtn.addEventListener("click", saveResumeToDatabase);
    }
});

async function loadWorkspaceData() {
    try {
        const localTemplateOverride = localStorage.getItem(`resume_template_id_${resume_id}`);
        const sessionTemplateOverride = sessionStorage.getItem("temp_template_id");
        activeTemplateId = localTemplateOverride ? Number(localTemplateOverride) : (sessionTemplateOverride ? Number(sessionTemplateOverride) : 1);

        // 1. Fetch templates metadata
        try {
            const templatesRes = await fetch(`${API_BASE_URL}/api/templates`);
            const templatesJson = await templatesRes.json();
            if (templatesJson.success && templatesJson.data) {
                templatesList = Array.isArray(templatesJson.data) ? templatesJson.data : (templatesJson.data.data || []);
            }
        } catch (e) {
            console.warn("Could not fetch templates list, using fallback.");
        }

        // 2. Check if resume_id exists in URL/DB
        const urlParams = new URLSearchParams(window.location.search);
        const urlResumeId = urlParams.get("resume_id") || localStorage.getItem("resume_id");

        if (urlResumeId && urlResumeId !== "null" && urlResumeId !== "undefined" && !urlParams.get("source")) {
            resume_id = urlResumeId;
            try {
                const response = await fetch(`${API_BASE_URL}/api/resume/editor/${resume_id}?user_id=${user_id}`);
                const result = await response.json();

                if (result.success && result.data) {
                    const d = result.data;
                    previewData = {
                        user_id: d.user_id || user_id || 1,
                        resume_id: d.resume_id || resume_id,
                        template_id: d.template_id || activeTemplateId,
                        resume_title: d.resume_title || "My Resume",
                        upload_confidence: d.upload_confidence || 100,
                        is_draft: d.is_draft !== undefined ? d.is_draft : true,
                        personal_details: d.personal && Object.keys(d.personal).length > 0 ? [d.personal] : [{}],
                        education: d.education || [],
                        experience: d.experience || [],
                        skills: d.skills || [],
                        projects: d.projects || [],
                        certifications: d.certifications || [],
                        languages: d.languages || [],
                        custom_sections: d.custom_sections || [],
                        section_status: d.section_status || {}
                    };

                    const badge = document.getElementById("draftStatusBadge");
                    if (badge) {
                        badge.innerHTML = `<i class="fa-solid fa-cloud-check"></i> ✓ Saved to Database`;
                        badge.style.color = "#10b981";
                    }
                }
            } catch (fetchErr) {
                console.warn("Could not fetch DB resume details, using session fallback:", fetchErr);
            }
        }

        if (!previewData) {
            // Temporary Session Draft from sessionStorage
            const tempDraftStr = sessionStorage.getItem("temp_resume_parsed_data");
            if (tempDraftStr) {
                console.log("Loading temporary upload draft from sessionStorage into editor...");
                const parsedObj = JSON.parse(tempDraftStr);
                previewData = {
                    user_id: user_id || 1,
                    resume_id: null,
                    template_id: activeTemplateId,
                    resume_title: parsedObj.resume_title || "Uploaded Resume Draft",
                    upload_confidence: parsedObj.upload_confidence || 95,
                    personal_details: [parsedObj.personal || {}],
                    education: parsedObj.education || [],
                    experience: parsedObj.experience || [],
                    skills: parsedObj.skills || [],
                    projects: parsedObj.projects || [],
                    certifications: parsedObj.certifications || [],
                    languages: parsedObj.languages || [],
                    custom_sections: parsedObj.custom_sections || []
                };
            } else {
                previewData = {
                    user_id: user_id || 1,
                    resume_id: null,
                    template_id: activeTemplateId,
                    resume_title: "My Resume Draft",
                    personal_details: [{}],
                    education: [],
                    experience: [],
                    skills: [],
                    projects: [],
                    certifications: [],
                    languages: [],
                    custom_sections: []
                };
            }

            const badge = document.getElementById("draftStatusBadge");
            if (badge) {
                badge.innerHTML = `<i class="fa-solid fa-clock"></i> Unsaved Session Draft`;
                badge.style.color = "#f59e0b";
            }
        }

        // Set navbar title
        const titleBadge = document.getElementById("resumeTitleBadge");
        if (titleBadge && previewData.resume_title) {
            titleBadge.textContent = previewData.resume_title;
        }

        if (previewData.template_id && !localTemplateOverride) {
            activeTemplateId = Number(previewData.template_id);
        }

        // Pre-fill form sections
        prefillContactsForm();
        renderEducationList();
        renderExperienceList();
        renderSkillsList();
        renderProjectsList();
        renderCertificationsList();
        renderCustomSectionsList();

        // Render Live Preview
        await renderLivePreview();

    } catch (err) {
        console.error("Error loading workspace details:", err);
    }
}

// ==========================================
// Form Pre-filling
// ==========================================
function prefillContactsForm() {
    const personal = previewData.personal_details[0] || {};
    document.getElementById("first_name").value = personal.first_name || "";
    document.getElementById("last_name").value = personal.last_name || "";
    document.getElementById("email").value = personal.email || "";
    document.getElementById("mobile").value = personal.mobile || "";
    document.getElementById("date_of_birth").value = personal.date_of_birth ? personal.date_of_birth.substring(0, 10) : "";
    document.getElementById("pincode").value = personal.pincode || "";
    document.getElementById("city").value = personal.city || "";
    document.getElementById("state").value = personal.state || "";
    document.getElementById("country").value = personal.country || "";
    document.getElementById("linkedin_url").value = personal.linkedin_url || "";
    document.getElementById("github_url").value = personal.github_url || "";
    document.getElementById("portfolio_url").value = personal.portfolio_url || "";
    document.getElementById("address").value = personal.address || "";
    document.getElementById("professional_summary").value = personal.professional_summary || "";
}

// ==========================================
// Live Preview Rendering
// ==========================================
async function renderLivePreview() {
    const container = document.getElementById("templateContainer");
    if (!container) return;

    const activeTemplate = templatesList.find(t => Number(t.template_id) === Number(activeTemplateId));
    const templateFolder = activeTemplate ? activeTemplate.template_folder : `Template-${String(activeTemplateId).padStart(3, '0')}`;

    try {
        await TemplateLoader.load(templateFolder, "templateContainer", previewData);
        adjustResumeScale();
    } catch (err) {
        console.error("Error rendering template preview:", err);
    }
}

// ==========================================
// Realtime input binding
// ==========================================
function setupRealtimeBinding() {
    const contactsInputs = [
        "first_name", "last_name", "email", "mobile", "date_of_birth", 
        "pincode", "city", "state", "country", "linkedin_url", 
        "github_url", "portfolio_url", "address", "professional_summary"
    ];

    contactsInputs.forEach(id => {
        const el = document.getElementById(id);
        if (el) {
            el.addEventListener("input", () => {
                if (!previewData.personal_details[0]) previewData.personal_details[0] = {};
                previewData.personal_details[0][id] = el.value;
                
                // Re-render preview instantly
                renderLivePreview();
                
                // Debounce and auto-save
                debouncedSaveContacts();
            });
        }
    });
}

// Debounce helper for contacts saving
let saveTimeout = null;
function debouncedSaveContacts() {
    clearTimeout(saveTimeout);
    saveTimeout = setTimeout(async () => {
        await saveContactsData();
    }, 1500);
}

async function saveContactsData() {
    const personal = previewData.personal_details[0] || {};
    try {
        const response = await fetch(`${API_BASE_URL}/api/personal/save`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                resume_personal_id: personal.resume_personal_id || null,
                resume_id: resume_id,
                first_name: document.getElementById("first_name").value,
                last_name: document.getElementById("last_name").value,
                email: document.getElementById("email").value,
                mobile: document.getElementById("mobile").value,
                date_of_birth: document.getElementById("date_of_birth").value || null,
                address: document.getElementById("address").value,
                city: document.getElementById("city").value,
                state: document.getElementById("state").value,
                country: document.getElementById("country").value,
                pincode: document.getElementById("pincode").value,
                linkedin_url: document.getElementById("linkedin_url").value,
                github_url: document.getElementById("github_url").value,
                portfolio_url: document.getElementById("portfolio_url").value,
                professional_summary: document.getElementById("professional_summary").value
            })
        });
        const result = await response.json();
        if ((result.error_cd === "00000" || result.error_cd === "0") && result.ref_id) {
            personal.resume_personal_id = Number(result.ref_id);
        }
    } catch (err) {
        console.error("Auto-save contacts error:", err);
    }
}

// ==========================================
// Wizard Navigation
// ==========================================
async function switchStep(newStep) {
    if (!stepsOrder.includes(newStep)) return;
    
    // Auto-save contacts details when leaving the contacts step
    if (currentStep === "contacts" && newStep !== "contacts") {
        try {
            await saveContactsData();
        } catch (err) {
            console.error("Error auto-saving contacts on step switch:", err);
        }
    }
    
    // Hide active step content, show new one
    document.getElementById(`step-${currentStep}`).style.display = "none";
    document.getElementById(`step-${newStep}`).style.display = "block";

    // Update steps nav bar styling
    document.querySelectorAll(".step-nav-item").forEach(item => {
        if (item.getAttribute("data-step") === newStep) {
            item.classList.add("active");
        } else {
            item.classList.remove("active");
        }
    });

    currentStep = newStep;
    const currentIndex = stepsOrder.indexOf(currentStep);

    // Manage Previous Button
    const btnPrev = document.getElementById("btnPrevStep");
    if (currentIndex === 0) {
        btnPrev.classList.add("disabled");
    } else {
        btnPrev.classList.remove("disabled");
    }

    // Manage Next Button Label
    const btnNext = document.getElementById("btnNextStep");
    if (currentIndex === stepsOrder.length - 1) {
        btnNext.innerHTML = 'Preview & Finish <i class="fa-solid fa-flag-checkered"></i>';
    } else {
        const nextStepName = stepsOrder[currentIndex + 1];
        const displayLabel = nextStepName.charAt(0).toUpperCase() + nextStepName.slice(1);
        btnNext.innerHTML = `Next: ${displayLabel} <i class="fa-solid fa-chevron-right"></i>`;
    }
}

// ==========================================
// Setup Event Listeners
// ==========================================
function setupEventListeners() {
    // 1. Navbar Navigation
    document.getElementById("btnBackToDashboard").addEventListener("click", () => {
        if (confirm("Go back to dashboard? Your changes are auto-saved.")) {
            window.location.href = "dashboard.html";
        }
    });

    document.getElementById("btnDownloadPDF").addEventListener("click", async () => {
        await saveContactsData();
        
        // Save state to database first
        const activeTemplate = templatesList.find(t => Number(t.template_id) === Number(activeTemplateId));
        const templateId = activeTemplate ? activeTemplate.template_id : activeTemplateId;
        const resumeName = previewData.resume_title || "Untitled Resume";
        
        try {
            const response = await fetch(`${API_BASE_URL}/api/resume/save-json`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    user_id: user_id,
                    resume_id: resume_id,
                    resume_name: resumeName,
                    template_id: templateId,
                    resume_json: previewData
                })
            });
            const result = await response.json();
            if (result.success) {
                console.log("Resume state saved to database successfully.");
            } else {
                console.warn("Failed to save resume state to database:", result.message);
            }
        } catch (err) {
            console.error("Error saving resume state to database:", err);
        }

        const resume = document.getElementById("templateContainer");
        const options = {
            margin: 0.3,
            filename: `${resumeName}.pdf`,
            image: {
                type: "jpeg",
                quality: 1
            },
            html2canvas: {
                scale: 2
            },
            jsPDF: {
                unit: "in",
                format: "a4",
                orientation: "portrait"
            }
        };
        html2pdf().set(options).from(resume).save();
    });

    // Toggle Full Screen Preview Pane
    document.getElementById("btnToggleFullScreen").addEventListener("click", () => {
        const container = document.querySelector(".editor-split-container");
        const isFullScreen = container.classList.toggle("full-screen-preview");
        
        const toggleIcon = document.getElementById("toggleIcon");
        const toggleText = document.getElementById("toggleText");
        
        if (isFullScreen) {
            toggleIcon.className = "fa-solid fa-compress";
            toggleText.textContent = "Split Screen";
        } else {
            toggleIcon.className = "fa-solid fa-expand";
            toggleText.textContent = "Full Screen";
        }
        
        // Dispatch window resize event so the templates refresh
        window.dispatchEvent(new Event('resize'));
    });

    // 2. Wizard Header Clicks
    document.querySelectorAll(".step-nav-item").forEach(item => {
        item.addEventListener("click", async () => {
            const targetStep = item.getAttribute("data-step");
            await switchStep(targetStep);
        });
    });

    // 3. Footer Navigation Buttons
    document.getElementById("btnPrevStep").addEventListener("click", async () => {
        const currentIndex = stepsOrder.indexOf(currentStep);
        if (currentIndex > 0) {
            await switchStep(stepsOrder[currentIndex - 1]);
        }
    });

    document.getElementById("btnNextStep").addEventListener("click", async () => {
        const currentIndex = stepsOrder.indexOf(currentStep);
        if (currentIndex === stepsOrder.length - 1) {
            // Save contacts and redirect to preview page
            await saveContactsData();
            window.location.href = "preview.html";
        } else {
            // Go to next step
            await switchStep(stepsOrder[currentIndex + 1]);
        }
    });

    // 4. Education Add Action
    document.getElementById("btnAddEducation").addEventListener("click", async () => {
        const degree = document.getElementById("degree").value;
        const institution = document.getElementById("institution").value;
        if (!degree || !institution) {
            alert("Degree and Institution name are required.");
            return;
        }

        try {
            const res = await fetch(`${API_BASE_URL}/api/education/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    resume_id: resume_id,
                    degree: degree,
                    institution: institution,
                    university: document.getElementById("university").value,
                    field_of_study: document.getElementById("field_of_study").value,
                    start_year: document.getElementById("start_year").value || null,
                    end_year: document.getElementById("end_year").value || null,
                    cgpa_percentage: document.getElementById("cgpa_percentage").value,
                    currently_studying: document.getElementById("currently_studying").checked
                })
            });
            const result = await res.json();
            alert(result.message);

            // Reset Form fields
            document.getElementById("degree").value = "";
            document.getElementById("institution").value = "";
            document.getElementById("university").value = "";
            document.getElementById("field_of_study").value = "";
            document.getElementById("start_year").value = "";
            document.getElementById("end_year").value = "";
            document.getElementById("cgpa_percentage").value = "";
            document.getElementById("currently_studying").checked = false;

            // Refresh List and Live Preview
            await reloadEducationData();
        } catch (err) {
            console.error("Save education error:", err);
        }
    });

    // 5. Experience Add Action
    document.getElementById("btnAddExperience").addEventListener("click", async () => {
        const company = document.getElementById("company_name").value;
        const type = document.getElementById("employment_type").value;
        if (!company || !type) {
            alert("Company Name and Employment Type are required.");
            return;
        }

        try {
            const res = await fetch(`${API_BASE_URL}/api/experience/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    resume_id: resume_id,
                    company_name: company,
                    job_title: document.getElementById("job_title").value,
                    employment_type: type,
                    location: document.getElementById("location").value,
                    start_date: document.getElementById("start_date").value || null,
                    end_date: document.getElementById("end_date").value || null,
                    currently_working: document.getElementById("currently_working").checked,
                    job_description: document.getElementById("job_description").value
                })
            });
            const result = await res.json();
            alert(result.message);

            // Reset Form fields
            document.getElementById("company_name").value = "";
            document.getElementById("job_title").value = "";
            document.getElementById("employment_type").value = "";
            document.getElementById("location").value = "";
            document.getElementById("start_date").value = "";
            document.getElementById("end_date").value = "";
            document.getElementById("currently_working").checked = false;
            document.getElementById("job_description").value = "";

            // Refresh List and Live Preview
            await reloadExperienceData();
        } catch (err) {
            console.error("Save experience error:", err);
        }
    });

    // 6. Skills Add Action
    document.getElementById("btnAddSkill").addEventListener("click", async () => {
        const skillName = document.getElementById("skill_name").value;
        if (!skillName) {
            alert("Skill name is required.");
            return;
        }

        try {
            const res = await fetch(`${API_BASE_URL}/api/skills/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    resume_id: resume_id,
                    skill_name: skillName,
                    skill_category: document.getElementById("skill_category").value,
                    skill_level: document.getElementById("skill_level").value,
                    experience_years: document.getElementById("experience_years").value || null
                })
            });
            const result = await res.json();
            alert(result.message);

            // Reset Form fields
            document.getElementById("skill_name").value = "";
            document.getElementById("skill_category").selectedIndex = 0;
            document.getElementById("skill_level").selectedIndex = 0;
            document.getElementById("experience_years").value = "";

            // Refresh List and Live Preview
            await reloadSkillsData();
        } catch (err) {
            console.error("Save skills error:", err);
        }
    });

    // 7. Projects Add Action
    document.getElementById("btnAddProject").addEventListener("click", async () => {
        const projectName = document.getElementById("project_name").value;
        if (!projectName) {
            alert("Project Name is required.");
            return;
        }

        try {
            const res = await fetch(`${API_BASE_URL}/api/projects/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    resume_id: resume_id,
                    project_name: projectName,
                    role: document.getElementById("role").value,
                    technologies_used: document.getElementById("technologies_used").value,
                    start_date: document.getElementById("proj_start_date").value || null,
                    end_date: document.getElementById("proj_end_date").value || null,
                    github_url: document.getElementById("proj_github_url").value,
                    live_project_url: document.getElementById("live_project_url").value,
                    project_description: document.getElementById("project_description").value
                })
            });
            const result = await res.json();
            alert(result.message);

            // Reset Form fields
            document.getElementById("project_name").value = "";
            document.getElementById("role").value = "";
            document.getElementById("technologies_used").value = "";
            document.getElementById("proj_start_date").value = "";
            document.getElementById("proj_end_date").value = "";
            document.getElementById("proj_github_url").value = "";
            document.getElementById("live_project_url").value = "";
            document.getElementById("project_description").value = "";

            // Refresh List and Live Preview
            await reloadProjectsData();
        } catch (err) {
            console.error("Save projects error:", err);
        }
    });

    // 8. Certifications Add Action
    document.getElementById("btnAddCertification").addEventListener("click", async () => {
        const certName = document.getElementById("certification_name").value;
        const issuer = document.getElementById("issuing_organization").value;
        if (!certName || !issuer) {
            alert("Certification Name and Issuing Organization are required.");
            return;
        }

        try {
            const res = await fetch(`${API_BASE_URL}/api/certifications/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    resume_id: resume_id,
                    certification_name: certName,
                    issuing_organization: issuer,
                    issue_date: document.getElementById("issue_date").value || null,
                    expiry_date: document.getElementById("expiry_date").value || null,
                    credential_id: document.getElementById("credential_id").value,
                    credential_url: document.getElementById("credential_url").value,
                    description: document.getElementById("cert_description").value
                })
            });
            const result = await res.json();
            alert(result.message);

            // Reset Form fields
            document.getElementById("certification_name").value = "";
            document.getElementById("issuing_organization").value = "";
            document.getElementById("issue_date").value = "";
            document.getElementById("expiry_date").value = "";
            document.getElementById("credential_id").value = "";
            document.getElementById("credential_url").value = "";
            document.getElementById("cert_description").value = "";

            // Refresh List and Live Preview
            await reloadCertificationsData();
        } catch (err) {
            console.error("Save certifications error:", err);
        }
    });

    // 9. Change Template Page Redirection
    document.getElementById("btnChangeTemplateWorkspace").addEventListener("click", () => {
        window.location.href = "select_template.html";
    });
}

// ==========================================
// List Rendering Functions
// ==========================================
function renderEducationList() {
    const tbody = document.getElementById("educationListBody");
    tbody.innerHTML = "";
    previewData.education.forEach(edu => {
        tbody.innerHTML += `
            <tr>
                <td><strong>${edu.degree}</strong></td>
                <td>${edu.institution}</td>
                <td>${edu.start_year} - ${edu.currently_studying ? "Present" : edu.end_year}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteEducation(${edu.education_id})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

function renderExperienceList() {
    const tbody = document.getElementById("experienceListBody");
    tbody.innerHTML = "";
    previewData.experience.forEach(exp => {
        tbody.innerHTML += `
            <tr>
                <td><strong>${exp.job_title}</strong></td>
                <td>${exp.company_name}</td>
                <td>${exp.start_date ? exp.start_date.substring(0, 7) : ""} - ${exp.currently_working ? "Present" : (exp.end_date ? exp.end_date.substring(0, 7) : "")}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteExperience(${exp.experience_id})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

function renderSkillsList() {
    const tbody = document.getElementById("skillsListBody");
    tbody.innerHTML = "";
    previewData.skills.forEach(skill => {
        tbody.innerHTML += `
            <tr>
                <td><strong>${skill.skill_name}</strong></td>
                <td>${skill.skill_category || "Other"}</td>
                <td>${skill.skill_level}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteSkill(${skill.skill_id})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

function renderProjectsList() {
    const tbody = document.getElementById("projectsListBody");
    tbody.innerHTML = "";
    previewData.projects.forEach(proj => {
        tbody.innerHTML += `
            <tr>
                <td><strong>${proj.project_name}</strong></td>
                <td>${proj.role || "N/A"}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteProject(${proj.project_id})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

function renderCertificationsList() {
    const tbody = document.getElementById("certificationsListBody");
    tbody.innerHTML = "";
    previewData.certifications.forEach(cert => {
        tbody.innerHTML += `
            <tr>
                <td><strong>${cert.certification_name}</strong></td>
                <td>${cert.issuing_organization}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteCertification(${cert.certification_id})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

function renderCustomSectionsList() {
    const tbody = document.getElementById("customSectionsListBody");
    if (!tbody) return;
    tbody.innerHTML = "";

    const list = previewData.custom_sections || [];
    if (list.length === 0) {
        tbody.innerHTML = `<tr><td colspan="3" style="text-align:center; color:#94a3b8;">No custom sections added.</td></tr>`;
        return;
    }

    list.forEach((cs, idx) => {
        const title = cs.section_title || "Custom Section";
        const items = Array.isArray(cs.section_data) ? cs.section_data.join(", ") : (cs.section_data || "");
        tbody.innerHTML += `
            <tr>
                <td><strong>${title}</strong></td>
                <td>${items}</td>
                <td>
                    <button class="delete-btn btn-sm" onclick="deleteCustomSection(${idx})">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        `;
    });
}

window.deleteCustomSection = function(idx) {
    if (confirm("Delete this custom section entry?")) {
        if (previewData.custom_sections && previewData.custom_sections[idx]) {
            previewData.custom_sections.splice(idx, 1);
            renderCustomSectionsList();
            renderLivePreview();
            markDirty();
        }
    }
};

const customSectionForm = document.getElementById("customSectionForm");
if (customSectionForm) {
    customSectionForm.addEventListener("submit", function(e) {
        e.preventDefault();
        const titleInput = document.getElementById("custom_section_title");
        const itemInput = document.getElementById("custom_section_item");
        if (!titleInput || !itemInput) return;

        const title = titleInput.value.trim();
        const item = itemInput.value.trim();
        if (!title || !item) return;

        if (!previewData.custom_sections) previewData.custom_sections = [];

        let existing = previewData.custom_sections.find(c => c.section_title.toLowerCase() === title.toLowerCase());
        if (existing) {
            if (!Array.isArray(existing.section_data)) existing.section_data = [existing.section_data];
            existing.section_data.push(item);
        } else {
            previewData.custom_sections.push({
                section_title: title,
                section_data: [item],
                display_order: previewData.custom_sections.length + 1
            });
        }

        titleInput.value = "";
        itemInput.value = "";

        renderCustomSectionsList();
        renderLivePreview();
        markDirty();
    });
}

// ==========================================
// Reload Sub-Data Functions
// ==========================================
async function reloadPreviewData() {
    try {
        const response = await fetch(
            `${API_BASE_URL}/api/resume/preview/list/${resume_id}?user_id=${user_id}`
        );
        const result = await response.json();
        
        if (result && result.data && result.data.length > 0) {
            previewData = result.data[0];
            
            // Setup initial default arrays if empty
            if (!previewData.personal_details) previewData.personal_details = [{}];
            if (!previewData.education) previewData.education = [];
            if (!previewData.experience) previewData.experience = [];
            if (!previewData.skills) previewData.skills = [];
            if (!previewData.projects) previewData.projects = [];
            if (!previewData.certifications) previewData.certifications = [];
        }
    } catch (err) {
        console.error("Error reloading preview data from server:", err);
    }
}

async function reloadEducationData() {
    await reloadPreviewData();
    renderEducationList();
    await renderLivePreview();
}

async function reloadExperienceData() {
    await reloadPreviewData();
    renderExperienceList();
    await renderLivePreview();
}

async function reloadSkillsData() {
    await reloadPreviewData();
    renderSkillsList();
    await renderLivePreview();
}

async function reloadProjectsData() {
    await reloadPreviewData();
    renderProjectsList();
    await renderLivePreview();
}

async function reloadCertificationsData() {
    await reloadPreviewData();
    renderCertificationsList();
    await renderLivePreview();
}

// ==========================================
// Delete Sub-Items Actions
// ==========================================
window.deleteEducation = async function(id) {
    if (confirm("Delete this education entry?")) {
        try {
            await fetch(`${API_BASE_URL}/api/education/delete/${id}`, { method: "DELETE" });
            await reloadEducationData();
        } catch (err) { console.error(err); }
    }
};

window.deleteExperience = async function(id) {
    if (confirm("Delete this experience entry?")) {
        try {
            await fetch(`${API_BASE_URL}/api/experience/delete/${id}`, { method: "DELETE" });
            await reloadExperienceData();
        } catch (err) { console.error(err); }
    }
};

window.deleteSkill = async function(id) {
    if (confirm("Delete this skill entry?")) {
        try {
            await fetch(`${API_BASE_URL}/api/skills/delete/${id}`, { method: "DELETE" });
            await reloadSkillsData();
        } catch (err) { console.error(err); }
    }
};

window.deleteProject = async function(id) {
    if (confirm("Delete this project entry?")) {
        try {
            await fetch(`${API_BASE_URL}/api/projects/delete/${id}`, { method: "DELETE" });
            await reloadProjectsData();
        } catch (err) { console.error(err); }
    }
};

window.deleteCertification = async function(id) {
    if (confirm("Delete this certification entry?")) {
        try {
            await fetch(`${API_BASE_URL}/api/certifications/delete/${id}`, { method: "DELETE" });
            await reloadCertificationsData();
        } catch (err) { console.error(err); }
    }
};

// ==========================================
// Auto-scale A4 Resume Page to Fit Viewport Width
// ==========================================
function adjustResumeScale() {
    const viewport = document.querySelector(".live-preview-viewport");
    const container = document.getElementById("templateContainer");
    if (!viewport || !container) return;

    const viewportWidth = viewport.clientWidth;
    const baseWidth = 794; // 210mm in pixels at 96 DPI
    const padding = 24;
    const availableWidth = Math.max(300, viewportWidth - padding);

    if (availableWidth < baseWidth) {
        const scale = availableWidth / baseWidth;
        container.style.transform = `scale(${scale})`;
        container.style.transformOrigin = "top center";
        container.style.width = `${baseWidth}px`;
        container.style.display = "block";
        
        const previewArea = document.querySelector(".preview-area");
        if (previewArea) {
            const containerHeight = Math.max(container.scrollHeight, container.offsetHeight, 1123);
            previewArea.style.minHeight = `${containerHeight * scale + 40}px`;
            previewArea.style.height = "auto";
            previewArea.style.width = `${availableWidth}px`;
            previewArea.style.overflow = "visible";
        }
    } else {
        container.style.transform = "none";
        container.style.width = "auto";
        container.style.display = "block";
        const previewArea = document.querySelector(".preview-area");
        if (previewArea) {
            previewArea.style.height = "auto";
            previewArea.style.minHeight = "auto";
            previewArea.style.width = "auto";
            previewArea.style.overflow = "visible";
        }
    }
}

// Attach listeners
window.addEventListener("resize", adjustResumeScale);

// ==========================================
// Helper: Persist All Uploaded Resume Sections to DB Tables
// ==========================================
async function checkAndSaveUploadedData(resumeId) {
    const parsedDataStr = localStorage.getItem("uploaded_resume_parsed_data");
    if (!parsedDataStr) return;

    try {
        console.log("Saving uploaded resume data to database tables via master PL/pgSQL function...");
        const data = JSON.parse(parsedDataStr);
        const userId = localStorage.getItem("user_id") || "1";
        const templateId = localStorage.getItem(`resume_template_id_${resumeId}`) || "1";
        const resumeTitle = localStorage.getItem("pending_resume_title") || "Uploaded Resume";

        // 1. Call Master Unified PL/pgSQL Function upr_insupd_hr_resume_full_upload_json
        const fullPayload = {
            user_id: userId,
            resume_id: resumeId,
            resume_title: resumeTitle,
            template_id: templateId,
            personal: data.personal || {},
            education: data.education || [],
            experience: data.experience || [],
            skills: data.skills || [],
            projects: data.projects || [],
            certifications: data.certifications || []
        };

        await fetch(`${API_BASE_URL}/api/resume/save-full-upload`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(fullPayload)
        });

        // 2. Individual section fallbacks
        if (data.personal) {
            const p = data.personal;
            await fetch(`${API_BASE_URL}/api/personal/save`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ resume_id: resumeId, ...p })
            });
        }

        if (Array.isArray(data.education) && data.education.length > 0) {
            for (const edu of data.education) {
                await fetch(`${API_BASE_URL}/api/education/save`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ resume_id: resumeId, ...edu })
                });
            }
        }

        if (Array.isArray(data.experience) && data.experience.length > 0) {
            for (const exp of data.experience) {
                await fetch(`${API_BASE_URL}/api/experience/save`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ resume_id: resumeId, ...exp })
                });
            }
        }

        if (Array.isArray(data.skills) && data.skills.length > 0) {
            for (const sk of data.skills) {
                await fetch(`${API_BASE_URL}/api/skills/save`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ resume_id: resumeId, ...sk })
                });
            }
        }

        if (Array.isArray(data.projects) && data.projects.length > 0) {
            for (const proj of data.projects) {
                await fetch(`${API_BASE_URL}/api/projects/save`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ resume_id: resumeId, ...proj })
                });
            }
        }

        console.log("All uploaded resume sections successfully saved into DB tables!");
        localStorage.removeItem("uploaded_resume_parsed_data");
    } catch (e) {
        console.error("Error in checkAndSaveUploadedData:", e);
    }
}



